###

###
GET https://qualif2.ihe.kereval.cloud/matchboxv3/metadata HTTP/1.1
Accept: application/fhir+json


###
POST https://qualif2.ihe.kereval.cloud/elm-simulator/fhir/ch/DocumentReference HTTP/1.1
Accept: application/fhir+json
Content-Type: application/fhir+json

./output/DocumentReference-7-DocumentReferenceStrict.json
 