###
GET https://ws.infreport-a.bag.admin.ch/ch-elm/v1/fhir/metadata HTTP/1.1
Accept: application/fhir+xml


### Provoke ERROR (returns 422, should return 500?)
POST https://ws.infreport-a.bag.admin.ch/ch-elm/v1/fhir/DocumentReference HTTP/1.1
Content-Type: application/fhir+json
Accept: application/fhir+json

TEST

### Successful POST
### need to remove 'http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict' from profile
POST https://ws.infreport-a.bag.admin.ch/ch-elm/v1/fhir/DocumentReference HTTP/1.1
Content-Type: application/fhir+json
Accept: application/fhir+json

< ./DocumentReference-1-DocumentReference.json

###
GET https://ws.infreport-a.bag.admin.ch/ch-elm/v1/fhir/DocumentReference/4822e056-41f5-4f65-b20e-86f9c874b9f8 HTTP/1.1
Content-Type: application/fhir+json
Accept: application/fhir+json

### returns list
GET https://ws.infreport-a.bag.admin.ch/ch-elm/v1/fhir/DocumentReference HTTP/1.1
Content-Type: application/fhir+json
Accept: application/fhir+json

### returns list of only in-progress
GET https://ws.infreport-a.bag.admin.ch/ch-elm/v1/fhir/DocumentReference?elm-status=in-progress HTTP/1.1
Content-Type: application/fhir+json
Accept: application/fhir+json

### returns list of only in-progress
GET https://ws.infreport-a.bag.admin.ch/ch-elm/v1/fhir/DocumentReference?elm-status=completed HTTP/1.1
Content-Type: application/fhir+json
Accept: application/fhir+json

### returns lists as of nov-8-23 (currently 1)
GET https://ws.infreport-a.bag.admin.ch/ch-elm/v1/fhir/DocumentReference?date=ge2023-11-08 HTTP/1.1
Content-Type: application/fhir+json
Accept: application/fhir+json

### returns lists as of nov-8-23 (currently 3)
GET https://ws.infreport-a.bag.admin.ch/ch-elm/v1/fhir/DocumentReference?date=lt2023-11-08 HTTP/1.1
Content-Type: application/fhir+json
Accept: application/fhir+json

### returns lists as of nov-8-23 (currently 1)
GET https://ws.infreport-a.bag.admin.ch/ch-elm/v1/fhir/DocumentReference?_lastUpdated=gt2023-11-08 HTTP/1.1
Content-Type: application/fhir+json
Accept: application/fhir+json

### returns lists as of nov-8-23 (currently 3)
GET https://ws.infreport-a.bag.admin.ch/ch-elm/v1/fhir/DocumentReference?_lastUpdated=lt2023-11-08 HTTP/1.1
Content-Type: application/fhir+json
Accept: application/fhir+json

### returns identified by identifer
GET https://ws.infreport-a.bag.admin.ch/ch-elm/v1/fhir/DocumentReference?identifier=urn:uuid:1901332d-6012-443f-9690-9291adb2e19d HTTP/1.1
Content-Type: application/fhir+json
Accept: application/fhir+json


### Duplicate POST, correct, but 52 second response time
### need to remove 'http://fhir.ch/ig/ch-elm/StructureDefinition/ch-elm-document-strict' from profile
POST https://ws.infreport-a.bag.admin.ch/ch-elm/v1/fhir/DocumentReference HTTP/1.1
Content-Type: application/fhir+json
Accept: application/fhir+json

< ./DocumentReference-1-DocumentReference.json
