###
GET https://ws.infreport-a.bag.admin.ch/ch-elm/v1/fhir/ValueSet HTTP/1.1
Accept: application/fhir+json


### via fullurl
GET https://ws.infreport-a.bag.admin.ch/ch-elm/v1/fhir/ValueSet?url=http%3A%2F%2Ffhir.ch%2Fig%2Fch-elm%2FValueSet%2Fch-elm-results-bot-spec HTTP/1.1
Accept: application/fhir+json


### not working
GET https://ws.infreport-a.bag.admin.ch/ch-elm/v1/fhir/ValueSet/ChElmResultsBotSpec HTTP/1.1
Accept: application/fhir+json

###
GET https://ws.infreport-a.bag.admin.ch/ch-elm/v1/fhir/ValueSet?url=http%3A%2F%2Ffhir.ch%2Fig%2Fch-elm%2FValueSet%2Fch-elm-results-laboratory-observation  HTTP/1.1
Accept: application/fhir+json


###
GET https://ws.infreport-a.bag.admin.ch/ch-elm/v1/fhir/ValueSet?url=http%3A%2F%2Ffhir.ch%2Fig%2Fch-elm%2FValueSet%2Fch-elm-results-geni-spec HTTP/1.1
Accept: application/fhir+json


### not yet implemented
GET https://ws.infreport-a.bag.admin.ch/ch-elm/v1/fhir/ConceptMap HTTP/1.1
Accept: application/fhir+json


###
GET https://ws.infreport-a.bag.admin.ch/ch-elm/v1/fhir/ValueSet/ch-elm-results-completion-vs HTTP/1.1
Accept: application/fhir+json

###
GET https://ws.infreport-a.bag.admin.ch/ch-elm/v1/fhir/ValueSet/ch-elm-results-geni-spec HTTP/1.1
Accept: application/fhir+json

###
GET https://ws.infreport-a.bag.admin.ch/ch-elm/v1/fhir/ValueSet/ch-elm-results-cpe-org HTTP/1.1
Accept: application/fhir+json

###
GET https://ws.infreport-a.bag.admin.ch/ch-elm/v1/fhir/ValueSet/ch-elm-results-laboratory-observation HTTP/1.1
Accept: application/fhir+json

###
GET https://ws.infreport-a.bag.admin.ch/ch-elm/v1/fhir/ValueSet/ch-elm-results-laboratory-observation HTTP/1.1
Accept: application/fhir+json


###
GET https://ws.infreport-a.bag.admin.ch/ch-elm/v1/fhir/ValueSet/ch-elm-interpretation-codes-pos-neg HTTP/1.1
Accept: application/fhir+json

###
GET https://ws.infreport-a.bag.admin.ch/ch-elm/v1/fhir/ValueSet/ch-elm-interpretation-codes-pos HTTP/1.1
Accept: application/fhir+json

###
GET https://ws.infreport-a.bag.admin.ch/ch-elm/v1/fhir/ValueSet/ch-elm-interpretation-codes-sero HTTP/1.1
Accept: application/fhir+json

###
GET https://ws.infreport-a.bag.admin.ch/ch-elm/v1/fhir/ValueSet/ch-elm-interpretation-codes-titer HTTP/1.1
Accept: application/fhir+json

### TOOD

GET https://ws.infreport-a.bag.admin.ch/ch-elm/v1/fhir/ValueSet/ch-elm-interpretation-codes-res-sus HTTP/1.1
Accept: application/fhir+json

###
GET https://ws.infreport-a.bag.admin.ch/ch-elm/v1/fhir/ValueSet/ch-elm-interpretation-codes-resistant-susceptible HTTP/1.1
Accept: application/fhir+json

