./docref.sh 10Doc-Legionella
./docref.sh 11Doc-Malaria
./docref.sh 12Doc-Monkeypox
./docref.sh 13Doc-Shigella
./docref.sh 14Doc-Neisseriameningitidis-confirmationtest
./docref.sh 15Doc-Measles-Seroconversion
./docref.sh 16Doc-Dengue-Titer
./docref.sh 17Doc-Neisseria
./docref.sh 18Doc-C-diphtheriae
./docref.sh 19Doc-S-pneumoniae
./docref.sh 20Doc-Vibrio-cholerae
./docref.sh 21Doc-HepatiteE
./docref.sh 22Doc-H-influenzae
./docref.sh 23Doc-F-tularensis
./docref.sh 24Doc-Chikungunya
./docref.sh 25Doc-tick-borne-encephalitis
./docref.sh 26Doc-HepatiteA
./docref.sh 28Doc-Listeria-monocytogenes
./docref.sh 29Doc-Rubella
./docref.sh 30Doc-Salmonella-enteritidis
./docref.sh 32Doc-Rubella-avidity
./docref.sh 33Doc-Salmonella-valueString
./docref.sh 34Doc-Brucella
./docref.sh 35Doc-CJD
./docref.sh 36Doc-Salmonella-paratyphi
./docref.sh 37Doc-Zika
./docref.sh 38Doc-Anthrax
./docref.sh 39Doc-Botulims
./docref.sh 40Doc-Crimean-Congo
./docref.sh 41Doc-Ebola
./docref.sh 42Doc-Lassa
./docref.sh 43Doc-Marburg
./docref.sh 44Doc-Mers-CoV
./docref.sh 45Doc-Sars-CoV
./docref.sh 46Doc-Yersinia-pestis
./docref.sh 47Doc-Variola
./docref.sh 48Doc-Mpox-Clade
./docref.sh 49Doc-HIV
./docref.sh 50Doc-HIV-viremia
./docref.sh 51Doc-Gelbfieber
./docref.sh 52Doc-Hantavirus
./docref.sh 53Doc-InfluenzaHxNy
./docref.sh 54Doc-Poliomyelitis
./docref.sh 55Doc-Tollwut
./docref.sh 56Doc-Trichinella-spiralis
./docref.sh 57Doc-West-Nile
./docref.sh 8Doc-HepatiteB
./docref.sh 9Doc-HepatiteC